
from pathlib import Path

import pandas as pd
from evidently import Report
from evidently.presets import DataDriftPreset


# --------------------------------------------------
# Paths
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

REFERENCE_FILE = BASE_DIR / "data" / "reference_data.csv"
PRODUCTION_FILE = BASE_DIR / "data" / "production_data.csv"
REPORT_DIR = BASE_DIR / "reports"
REPORT_FILE = REPORT_DIR / "drift_report.html"


# --------------------------------------------------
# Load data
# --------------------------------------------------

def load_data():

    reference_df = pd.read_csv(
        REFERENCE_FILE
    )

    production_df = pd.read_csv(
        PRODUCTION_FILE
    )

    return reference_df, production_df


# --------------------------------------------------
# Prepare data
# --------------------------------------------------

def prepare_data(
    reference_df: pd.DataFrame,
    production_df: pd.DataFrame
):

    # Columns generated by the inference system.
    # These should NOT be used for input data drift.
    monitoring_columns = [
        "prediction",
        "latency_ms",
        "timestamp",
    ]

    columns_to_remove = [
        column
        for column in monitoring_columns
        if column in production_df.columns
    ]

    production_df = production_df.drop(
        columns=columns_to_remove
    )

    # Only compare columns present in both datasets.
    common_columns = [
        column
        for column in reference_df.columns
        if column in production_df.columns
    ]

    reference_df = reference_df[common_columns]
    production_df = production_df[common_columns]

    return reference_df, production_df


# --------------------------------------------------
# Generate drift report
# --------------------------------------------------

def generate_drift_report(
    reference_df: pd.DataFrame,
    production_df: pd.DataFrame
):

    report = Report(
        [
            DataDriftPreset()
        ]
    )

    result = report.run(
        reference_data=reference_df,
        current_data=production_df
    )

    REPORT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    result.save_html(
        str(REPORT_FILE)
    )

    # Verify that the file was actually created.
    if not REPORT_FILE.exists():

        raise RuntimeError(
            f"Drift report was not created: "
            f"{REPORT_FILE}"
        )

    print(
        f"Drift report successfully created: "
        f"{REPORT_FILE}"
    )


# --------------------------------------------------
# Main
# --------------------------------------------------

def main():

    print("Loading datasets...")

    reference_df, production_df = load_data()

    print(
        f"Reference dataset: {reference_df.shape}"
    )

    print(
        f"Production dataset: {production_df.shape}"
    )

    reference_df, production_df = prepare_data(
        reference_df,
        production_df
    )

    print(
        f"Comparing {len(reference_df.columns)} features..."
    )

    generate_drift_report(
        reference_df,
        production_df
    )


if __name__ == "__main__":
    main()

